### ISSUE TITLE
Performance ?

### ISSUE THREAD

**Issue by piti-diablotin** [melmorabity/plugin.video.francetv#15]
Hello,

I am using this extension to watch France TV from Belgium. I use a French VPN with proxy configured in Kodi settings to bypass geolocalisation. It works but it is really not reliable. Stream blocks very often.

If I do the same with firefox: same VPN + same proxy in firefox and go to france.tv website to watch live, or replay, it is very smooth.

What could be the problem ?

Thank you in advance for this nice addon !

**Comment by melmorabity** [comment]
No VPN support, sorry.
