### ISSUE TITLE
addon stopped working

### ISSUE THREAD

**Issue by pedroapero** [melmorabity/plugin.video.francetv#3]
This plugin used to work just fine (I last used it a couple of weeks ago). Since yesterday, I'm no longer able to access anything.

I get the «error, check envents log» popup when I try any of the entries in the menu, and then I get an empty list.

I looked in the Kodi events log (enabled), but there is no addon error here.

Any help would be appreciated. Thanks for this addon!

**Comment by himarmajhool** [comment]
France.tv recently implemented a logged-only view policy. The plugin doesn't work anymore because you cannot watch France.TV programs unless you have a valid account and are logged in.

**Comment by melmorabity** [comment]
> France.tv recently implemented a logged-only view policy. The plugin doesn't work anymore because you cannot watch France.TV programs unless you have a valid account and are logged in.

No. The addon relies on the france.tv mobile API, which doesn't require any authentication.

I currently have no issue with the addon as distributed by the official repository, on Kodi 19, from France.

@pedroapero : could you provide your operating system, your Kodi version and the country from which you are connected?

**Comment by Mrcuve0** [comment]
Hi! I'm having playback issues too.
I'm on Libreelec 10, Kodi 19.1 and I've just installed the addon (latest release, all dependencies have "matrix" in their version name).
I'm connecting from Italy through ProtonVPN (using VPN manager) to their French servers (217.138.207.229 Ile-de-France M247 ltd.).

All the informations for each channel are up-to-date (nom de l'emission par example) but everytime I start the stream it throws an "One or more items failed to play. Check the log for more information about this message".

I'll attach here the log, the errors can be found (for instance) at line 372. The http connection throws back a 403 status message, could this be VPN related? I also tried with Catch Up TV and More addon and a similar error is thrown (you can find it in this very same log).

Thank you for your time! Don't hesitate to ask me further details!

[01_KODI.log](https://github.com/melmorabity/plugin.video.francetv/files/7085340/01_KODI.log)

**Comment by pedroapero** [comment]
> @pedroapero : could you provide your operating system, your Kodi version and the country from which you are connected?

I'm using CoreElec 9.2.7 on aarch64 (Linux 4.9.113; Kodi 18.9.0) from France.

**Comment by pedroapero** [comment]
The plugin is working again now. My Kodi version got updated but I'm not sure if that's related! We can probably close this if other users confirm.

**Comment by Mrcuve0** [comment]
I can confirm the streaming is now working (on both addons, francetv and catchuptv). I tried searching for updates but i cannot say for sure if the addons were actually updated or not.
